-- ExchangeFlow: 초기 스키마 설정
-- Snowflake Worksheet에서 1회 실행 (ACCOUNTADMIN 또는 적절한 권한 role)

CREATE WAREHOUSE IF NOT EXISTS EXCHANGEFLOW_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS EXCHANGEFLOW;

CREATE SCHEMA IF NOT EXISTS EXCHANGEFLOW.RAW;
CREATE SCHEMA IF NOT EXISTS EXCHANGEFLOW.STAGING;
CREATE SCHEMA IF NOT EXISTS EXCHANGEFLOW.MART;

USE DATABASE EXCHANGEFLOW;
USE WAREHOUSE EXCHANGEFLOW_WH;

-- RAW: API 응답 JSON을 그대로 VARIANT로 적재
-- STRIP_OUTER_ARRAY=TRUE 이므로 배열의 통화별 원소가 각각 한 행으로 들어온다
CREATE FILE FORMAT IF NOT EXISTS RAW.JSON_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = TRUE;

CREATE STAGE IF NOT EXISTS RAW.RAW_STAGE
    FILE_FORMAT = RAW.JSON_FORMAT;

CREATE TABLE IF NOT EXISTS RAW.EXCHANGE_RATE_RAW (
    raw_data   VARIANT,
    file_name  STRING,
    loaded_at  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- STAGING.EXCHANGE_RATE_STG / MART.EXCHANGE_RATE_DAILY 테이블은
-- dbt(`dbt/`)가 첫 실행 시 모델 정의에 맞춰 직접 생성/관리한다 (incremental + merge).
-- 여기서 별도로 CREATE TABLE 하지 않는다.
